name: Release NPM - Publish to github packages

on:
  release:
    types: [released]

env:
  NPM_REGISTRY_PROTOCOL: 'https'
  NPM_REGISTRY_HOST: 'npm.pkg.github.com'

jobs:
  packages:
    permissions:
      packages: write
      contents: read
    name: Publish to npm registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify registry url
        run: |
          echo 'NPM_REGISTRY_URL: ${{ env.NPM_REGISTRY_PROTOCOL }}://${{ env.NPM_REGISTRY_HOST }}'
          echo "If this fails, try adding the following to your /etc/docker/daemon.json file:"
          echo '{
            "insecure-registries": ["${{ env.NPM_REGISTRY_PROTOCOL }}//${{ env.NPM_REGISTRY_HOST }}"],
            "mtu": 1450
          }'
          curl -v ${{ env.NPM_REGISTRY_PROTOCOL }}://${{ env.NPM_REGISTRY_HOST }} --insecure
        continue-on-error: true

      - uses: pnpm/action-setup@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          registry-url: ${{ env.NPM_REGISTRY_PROTOCOL }}://${{ env.NPM_REGISTRY_HOST }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          scope: '@levicape'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install and test
        run: |
          pnpm install;
          pnpm run test;
      - name: Increment version
        run: | 
          export PREID=$RELEVANT_SHA;
          export PREID=${PREID:0:10};
          export ARGS="--git-tag-version=false --commit-hooks=false";
          npm version ${{ github.event.release.tag_name }}-$PREID.${{ github.run_number }} $ARGS --allow-same-version;
        env:
          RELEVANT_SHA: ${{ github.event.release.target_commitish || github.sha }}          
      - name: Publish to npm registry
        if: success()
        run: |
          pnpm publish --no-git-checks;
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}