name: "on Push: Test package"
on:
  push:
    branches:
      - main
      - develop
      - mr-*
      - feature/*
      - feature/*/*
      - feature/*/*/*
      - hotfix/*
      - release/*
      - bugfix/*
      - ci/*
      - docs/*
      - refactor/*
      - test/*
      - fix/*
      - update/*
      - revert/*
      - merge/*
      - deploy
env:
  NPM_REGISTRY_PROTOCOL: 'https'
  NPM_REGISTRY_HOST: 'npm.pkg.github.com'
# TODO: Bundle node and pnpm in a docker image
jobs:
  # module:
  #   name: Verify test:module
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: pnpm/action-setup@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "22.12.0"
  #         registry-url: ${{ env.NPM_REGISTRY_PROTOCOL }}://${{ env.NPM_REGISTRY_HOST }}
  #         cache: 'pnpm'
  #         cache-dependency-path: pnpm-lock.yaml
  #         scope: '@levicape'
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Cache node modules
  #       id: cache-npm
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: cache-node-modules
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-build-${{ env.cache-name }}-
  #           ${{ runner.os }}-build-
  #           ${{ runner.os }}-

  #     - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
  #       name: List the state of node modules
  #       continue-on-error: true
  #       run: pnpm list
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Install dependencies
  #       run: |
  #         pnpm install;
  #         pnpm run build:ci;

  #     - name: Run unit tests
  #       run: pnpm run test:unit

  #     - name: Run lint
  #       run: pnpm run lint
  canary:
    name: Verify test:canary
    runs-on: ${{ vars.RUNNER }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.12.0"
          registry-url: ${{ env.NPM_REGISTRY_PROTOCOL }}://${{ env.NPM_REGISTRY_HOST }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          scope: '@levicape'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: pnpm list
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          pnpm install;
          pnpm run build:ci;

      - name: Run canary tests
        run: pnpm run test:canary